### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by woook**
Adds additional Swiss Army Knife app to split multiallelics to workaround BSVI not being able to handle multiallelic variants (specifically 0/1/2 genotypes).

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/5)

### CODE REVIEW

**Review by carmelinacharalambous — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/5)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @carmelinacharalambous and @woook)

___
*[dxworkflow.json, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/5#-MVvzqx40Jof7u7faW_q:-MVvzqx55FXa9pv7bfD8:b-iz8b8l) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/880b0af31ca671fdefd66a0cd2bc484260309ac4/dxworkflow.json#L55)):*
> ```JSON
>       "folder": "bsvi_vcfs",
>       "input": {
>         "cmd": "sh remove_germline_risk_v*.sh",
> ```

this should be included in v1.2.0

**Comment by woook** [comment]
___
*[dxworkflow.json, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/5#-MVvzqx40Jof7u7faW_q:-MVw1U393cUYo1ovwNEe:b3dq0ow) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/880b0af31ca671fdefd66a0cd2bc484260309ac4/dxworkflow.json#L55)):*
<details><summary><i>Previously, carmelinacharalambous wrote…</i></summary><blockquote>

this should be included in v1.2.0 
</blockquote></details>

it's got shuffled in the json and now present ~15 lines further down

**Comment by carmelinacharalambous** [comment]
___
*[dxworkflow.json, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/5#-MVvzqx40Jof7u7faW_q:-MVw1zOH9Oa1sgaZ-zmB:bqo32al) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/880b0af31ca671fdefd66a0cd2bc484260309ac4/dxworkflow.json#L55)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

it's got shuffled in the json and now present ~15 lines further down
</blockquote></details>

identified script is present in json

**Review by carmelinacharalambous — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @woook)

**Pull request merged**
