### PR TITLE
v1.12.0

### PR DESCRIPTION
**Pull request by jethror1**
- Update eggd_vcf_handler_for_uranus to v2.7.0
- Update eggd_sompy to v1.0.2
- Removal of eggd_generate_vcf_metadata
- Removal of all external inputs to go to conductor assay config file
- Switch of stage IDs to human readable names for nicer reading times

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`dxworkflow.json` line 181 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66LkF3GCXrDIh6PYB:-NU66LkF3GCXrDIh6PYC:bep8ojj) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L181)):*
> ```JSON
>     {
>       "id": "stage-somalier_extract",
>       "executable": "applet-G5YG118433Gk5xPbGx172fq8",
> ```

Im sure there's a new app?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 213 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66Rwe0MrQ3GnKp2qE:-NU66Rwe0MrQ3GnKp2qF:b-u4whw0) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L213)):*
> ```JSON
>           "$dnanexus_link": {
>             "outputField": "variants_vcf",
>             "stage": "stage-G0qpY1Q433GpzBp958KJYfBK"
> ```

update this

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 206 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66V1HDvd0dw2NXtDW:-NU66V1HDvd0dw2NXtDX:bbfv6s) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L206)):*
> ```JSON
>     },
>     {
>       "id": "stage-GJq28Pj4y1bKyQJkBjJbJpP7",
> ```

update this too

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 208 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66cSr9hy-7r1XT9Lp:-NU66cSr9hy-7r1XT9Lq:b-rb078u) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L208)):*
> ```JSON
>       "id": "stage-GJq28Pj4y1bKyQJkBjJbJpP7",
>       "executable": "app-eggd_sompy/1.0.1",
>       "folder": "eggd_sompy_v1.0.1",
> ```

new version 1.0.2 out

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 252 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66g8g4bDtL412zfr_:-NU66g8g4bDtL412zfra:bfawevd) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L252)):*
> ```JSON
>           }
>         },
>         "query_vcf_string": "Oncospan"
> ```

remove this too

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 219 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66kIJ3Mbh8vlfP1yh:-NU66kIJ3Mbh8vlfP1yi:b-rt231s) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L219)):*
> ```JSON
>           "$dnanexus_link": {
>             "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>             "id": "file-GF3BJJj433Gzgy6qJGx52Gjg"
> ```

remove all sompy inputs too pls

**Review by Aisha-D — COMMENTED** [review]
Do you want to match the output folders to the output folders in conductor produces?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-:-NU66v8c7SBnjHLTmS2j:b-a6adeg)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @jethror1)

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 16 at r4](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU68IhG8N1A1ZE18TQ3:-NU68IhG8N1A1ZE18TQ4:bye6t9z) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/9a3de5748b05161d71296f35f848e70bf2c306bb/README.md#L16)):*
> ```Markdown
> |sentieon_bwa_mem   |3.2.0|
> |sentieon_bam_to_vcf|3.2.0|
> |eggd_vcf_handler_for_uranus|2.6.1|
> ```

did you not update handler app?

**Review by jethror1 — COMMENTED** [review]
doesn't really matter as conductor sets them anyway and overwrites them

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-:-NU6BQmy1Ygk3dGvcF_b:b-folnb7)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @Aisha-D)

___
*[`dxworkflow.json` line 181 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66LkF3GCXrDIh6PYB:-NU6BVcs2XE1_DlX4kCZ:b4tr9gq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L181)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

Im sure there's a new app? 
</blockquote></details>

fixed yes sorry I did a dumb
___
*[`dxworkflow.json` line 206 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66V1HDvd0dw2NXtDW:-NU6BYPC1HyZG39JWLiJ:b4tr9gq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L206)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

update this too
</blockquote></details>

fixed yes sorry I did a dumb
___
*[`dxworkflow.json` line 208 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66cSr9hy-7r1XT9Lp:-NU6BZK3127Yk-mdZbdA:b4tr9gq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L208)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

new version 1.0.2 out
</blockquote></details>

fixed yes sorry I did a dumb
___
*[`dxworkflow.json` line 213 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66Rwe0MrQ3GnKp2qE:-NU6BZnF8lOK6bFsvcEg:b4tr9gq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L213)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

update this
</blockquote></details>

fixed yes sorry I did a dumb
___
*[`dxworkflow.json` line 219 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66kIJ3Mbh8vlfP1yh:-NU6B_CF35vZw-_hlnpV:b4tr9gq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L219)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

remove all sompy inputs too pls
</blockquote></details>

fixed yes sorry I did a dumb
___
*[`dxworkflow.json` line 252 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU66g8g4bDtL412zfr_:-NU6B_ow1esOG0QWDjQU:b4tr9gq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/4d54c1cc0a1479b1febc9330cdb511dfc6354e88/dxworkflow.json#L252)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

remove this too
</blockquote></details>

fixed yes sorry I did a dumb
___
*[`README.md` line 16 at r4](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU68IhG8N1A1ZE18TQ3:-NU6BaLnAG486BbeBuwB:b4tr9gq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/9a3de5748b05161d71296f35f848e70bf2c306bb/README.md#L16)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

did you not update handler app?
</blockquote></details>

fixed yes sorry I did a dumb

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 9 at r5](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU6D06a0kw1ZQNeTsHu:-NU6D06a0kw1ZQNeTsHv:b7x1foq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/1249da44c82cc5c3fdecf1be415309e967e66838/dxworkflow.json#L9)):*
> ```JSON
>       "id": "stage-sentieon_bwa",
>       "executable": "app-sentieon-bwa/3.2.0",
>       "folder": "sentieon_bam"
> ```

update this to match conductor output

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 14 at r5](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-NU6D42o43hgGoHebizF:-NU6D42o43hgGoHebizG:b7x1foq) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/1249da44c82cc5c3fdecf1be415309e967e66838/dxworkflow.json#L14)):*
> ```JSON
>       "id": "stage-sentieon_tnbam",
>       "executable": "app-sentieon-tnbam/3.2.0",
>       "folder": "sentieon_vcfs",
> ```

update this to match conductor output

**Review by Aisha-D — COMMENTED** [review]
ahh okay :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-:-NU6DaI_AIsxiIQekL_D:b26x35c)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jethror1)

**Review by Aisha-D — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24#-:-NU6Dgrg5rc9-Tgfuh12:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved

**Review by Aisha-D — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
