### PR TITLE
URA 546 v2.0.0

### PR DESCRIPTION
**Pull request by nadia31415**
Updated executable and folder fields for:
- verifybamid
- picard 
- samtools
- mosdepth

Updated README and dx json and workflow image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/29)

### CODE REVIEW

**Review by cnascim1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/29)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @nadia31415)

___
*[`README.md` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/29#-Nz2IFGD0BW3yBn_4U03:-Nz2IFGD0BW3yBn_4U04:b-zbr5ky) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/431f2bfb561d5bac6016794471f5fe88c0040bab/README.md#L21)):*
> ```Markdown
> |sentieon-tnbam|3.2.0|
> <<<<<<< HEAD
> >>>>>>> dd5b5342338a78ebdad9001ca998eda8a521dca1
> ```

the commits are still showing, I wonder if it is because of merging ours together

**Review by cnascim1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/29)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadia31415)

**Review by cnascim1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/29)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nadia31415)

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/29)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`README.md` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_uranus_main_workflow/29#-Nz2IFGD0BW3yBn_4U03:-Nz2SNCCEDHETXZmUNEd:b-efrqcb) ([raw file](https://github.com/eastgenomics/eggd_uranus_main_workflow/blob/431f2bfb561d5bac6016794471f5fe88c0040bab/README.md#L21)):*
<details><summary><i>Previously, cnascim1 wrote…</i></summary><blockquote>

the commits are still showing, I wonder if it is because of merging ours together
</blockquote></details>

The commits were showing to either keep current changes or accept new changes since changes were made in the development branch after this PR, I have rectified this by accepting changes from the dev branch

**Pull request merged**
